[project]
name = "resume-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "imabsaar007", email = "imabsaar007@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "groq>=1.7.0",
    "pydantic>=2.13.5",
    "pypdf>=6.18.1",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
resume-parser = "resume_parser:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
